### ISSUE TITLE
‘Subscribe to newsletter’ form

### ISSUE THREAD

**Issue by mfilej** [SloveniaRUG/SloveniaRUG.github.io#12]
> Nekam v header bi jaz porinil še subscribe to newsletter formo. Mogoče samo okenček s Subscribe to our newsletter placeholderjem pod knofoma? Pa na enter submit na mailchimp? 
> Tole je ena generated forma:

```
<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//rug.us8.list-manage.com/subscribe/post?u=fb83f064e1568f91a529d959f&amp;id=4ac5bafc63" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address </label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_fb83f064e1568f91a529d959f_4ac5bafc63" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
```

**Comment by mfilej** [comment]
Sprobal sem dve varianti in rezultat je precej … :hankey: 

![2015-04-04 at 09 01](https://cloud.githubusercontent.com/assets/3621/6991824/90bbe778-daab-11e4-93a7-f092bea2e620.png)
![2015-04-04 at 09 02](https://cloud.githubusercontent.com/assets/3621/6991825/92b8b1be-daab-11e4-9c85-231d3919e35c.png)

Pol sem pa malo gledal tisti "past meetups" link in se mi zdi cisto prevelik glede na pomembnost. Saj imamo v bistvu spodaj cel grid postov, ki so past meetupi.

Tako da bi pomojem lahko tisti prostor uporabili za newsletter link. Nekaj takega:

![2015-04-04 at 09 17](https://cloud.githubusercontent.com/assets/3621/6991831/cf2b1ec0-daab-11e4-90b5-7d4e81940344.png)

Pa imamo hkrati spodaj se manjsa linka na newsletter archive in  past meetups. Mnenje?

A je mogoce mozno dobit link do te forme (brez validation errorjev)? http://rug.us8.list-manage.com/subscribe/post?u=fb83f064e1568f91a529d959f&amp;id=4ac5bafc63

@mrfoto prosim poglej tisti "archive" link na newsletter formi, mislim da pelje na star arhiv na meetup.com

**Comment by mrfoto** [comment]
Ja, tadruga opcija je ql, edino mal natlačen zgleda tekst notr :confused: 
Tule je samo forma: http://rug.us8.list-manage.com/subscribe?u=fb83f064e1568f91a529d959f&id=4ac5bafc63
Lahko je pa ta knof ubistvu email input field in na enter submita. Sploh glede na to da že zgleda drgač. Tle je naked forma:
```
<!-- Begin MailChimp Signup Form -->
<div id="mc_embed_signup">
<form action="//rug.us8.list-manage.com/subscribe/post?u=fb83f064e1568f91a529d959f&amp;id=4ac5bafc63" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address </label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_fb83f064e1568f91a529d959f_4ac5bafc63" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
```

Tule je mailchimp arhiv: http://us8.campaign-archive2.com/home/?u=fb83f064e1568f91a529d959f&id=4ac5bafc63

**Comment by mrfoto** [comment]
Drgač pa great job glede vsega :+1: Očitno bomo odprl Slack :smile:

**Comment by mfilej** [comment]
Hehe. :grimacing: 

> Lahko je pa ta knof ubistvu email input field in na enter submita.

Te variante se malo bojim, da ne bo prav očitno, da je text field, ker ni gumba za submitat.

> Ja, tadruga opcija je ql, edino mal natlačen zgleda tekst notr

A to si mislu 2. al 3. screenshot? Ker pri 3. bi lahko malo potweakal dimenzije, da bi malo bolj dihalo.

Jaz navijam za tole varianto (malo sem se potweakal fonte in paddinge, da bolj diha; po potrebi bi lahko bila gumba se malo sirsa):

![2015-04-09 at 09 05](https://cloud.githubusercontent.com/assets/3621/7061881/909053ca-de97-11e4-8294-34989a6e0634.png)

**Comment by mrfoto** [comment]
Jah nekak bi rad mel takoj formo, ne da morš it na nek drug page. Sej če bo kdo hotu kliknt subscribe in bo začel carret utripat mu bo jasn da sam mail napiše. Loh se pa on input še knof za submit prkaže. Torej najprej nč, ko pa začne mail tipkat not, ga pa pokažeš. Pa na enter more valda tut submitat. Kaj mislš?

**Comment by mfilej** [comment]
Sliši se mučeniško (glede na mailchimpov markup). :laughing: Ampak bom sprobal.

**Comment by mrfoto** [comment]
Pa sj loh vse vn pomečeš. Sam hidden field mora bit pa input za mail pa tja se mora submittat. Dobiš za :beers: :smile:

**Comment by mfilej** [comment]
Done.
